export const data = [
  {
    id: "ID_1",
    case_number: "",
    name: "john",
    post: "Teacher",
    grade: "10",
    cohort: "1",
    teacher: "t",
    current_status: "Tracked",
    date_started: "11-10-20",
    status: "yes"
  },
  {
    id: "ID_2",
    case_number: "",
    name: "john1",
    post: "Teacher",
    grade: "10",
    cohort: "1",
    teacher: "t",
    current_status: "Tracked",
    date_started: "11-10-20",
    status: "yes"
  },
  {
    id: "ID_3",
    case_number: "",
    name: "john2",
    post: "Teacher",
    grade: "10",
    cohort: "1",
    teacher: "t",
    current_status: "Tracked",
    date_started: "11-10-ID_20",
    status: "yes"
  },
  {
    id: "ID_4",
    case_number: "",
    name: "john3",
    post: "Teacher",
    grade: "10",
    cohort: "1",
    teacher: "t",
    current_status: "Tracked",
    date_started: "11-10-20",
    status: "yes"
  },
  {
    id: "ID_5",
    case_number: "",
    name: "john4",
    post: "Teacher",
    grade: "10",
    cohort: "1",
    teacher: "t",
    current_status: "Tracked",
    date_started: "11-10-20",
    status: "yes"
  },
  {
    id: "ID_6",
    case_number: "",
    name: "john5",
    post: "Teacher",
    grade: "10",
    cohort: "1",
    teacher: "t",
    current_status: "Tracked",
    date_started: "11-10-20",
    status: "yes"
  },
  {
    id: "ID_7",
    case_number: "",
    name: "john6",
    post: "Teacher",
    grade: "10",
    cohort: "1",
    teacher: "t",
    current_status: "Tracked",
    date_started: "11-10-20",
    status: "yes"
  },
  {
    id: "ID_8",
    case_number: "",
    name: "john7",
    post: "Teacher",
    grade: "10",
    cohort: "1",
    teacher: "t",
    current_status: "Tracked",
    date_started: "11-10-20",
    status: "yes"
  },
  {
    id: "ID_9",
    case_number: "",
    name: "john8",
    post: "Teacher",
    grade: "10",
    cohort: "1",
    teacher: "t",
    current_status: "Returned",
    date_started: "11-10-20",
    status: "yes"
  } // eslint-disable-line
];
export const data1 = [
  {
    number: "1",
    name: "john",
    post: "Teacher",
    date_tracked: "10-10-20",
    date_notified: "10-10-20",
    date_of_contact: "10-10-20",
    s_o_covid: "returned",
    status: "yes"
  },
  {
    number: "1",
    name: "john",
    post: "Teacher",
    date_tracked: "10-10-20",
    date_notified: "10-10-20",
    date_of_contact: "10-10-20",
    s_o_covid: "returned",
    status: "yes"
  },
  {
    number: "1",
    name: "robin",
    post: "Teacher",
    date_tracked: "10-10-20",
    date_notified: "10-10-20",
    date_of_contact: "10-10-20",
    s_o_covid: "returned",
    status: "yes"
  },
  {
    number: "1",
    name: "robin",
    post: "Teacher",
    date_tracked: "10-10-20",
    date_notified: "10-10-20",
    date_of_contact: "10-10-20",
    s_o_covid: "returned",
    status: "yes"
  },
  {
    number: "1",
    name: "robin",
    post: "Teacher",
    date_tracked: "10-10-20",
    date_notified: "10-10-20",
    date_of_contact: "10-10-20",
    s_o_covid: "returned",
    status: "yes"
  } // eslint-disable-line
];
export const data3 = {
  initialData: {
    studentIDList: ["1", "2"],
    caseNumber: "",
    lastName: "",
    firstName: "",
    grade: ["1", "2", "4"],
    teacher: ["wqwq", "wqwq", "wwwq"],
    isHome: true,
    PG: true,
    date: "",
    reference: "",
    selectSymptoms: ["wqwq", "aawqwq", "wwwq"],
    temprature: ["10", "20", "30"],
    affectedArea: ["a", "b", "c"],
    isStafNotified: true,
    selectSymptomsID: [],
    studentID: "",
    teacherID: "",
    gradeID: "",
    tempratureID: "",
    affectedAreaID: ""
  },
  HourTracker: {
    checkInDate: "",
    status: ["Return to school", "Remote  Quarantine"],
    symptoms: ["ew", "ewew", "ewew"],
    changeRemote: ["ew", "ewew", "ewew"],
    teacherNotified: ["ew", "ewew", "ewew"],
    sisChangeConducted: ["ew", "ewew", "ewew"],
    handoutProvided: ["ew", "ewew", "ewew"],
    covidDate: "",
    currentStatus: "",
    statusID: "",
    symptomsID: [],
    changeRemoteID: "",
    teacherNotifiedID: "",
    sisChangeConductedID: "",
    handoutProvidedID: ""
  },
  ReturnTracker: {
    checkInDate: "",
    anticipatedReturnDate: "",
    teacherNotifiedReturn: ["re", "Rere", "Rer"],
    teacherNotifiedReturnDate: ["ss", "dwd", "dww"],
    studentNegativeCovidTest: ["Re", "Rere", "Re"],
    studentNegativeCovidTestDate: "",
    studentReturn: ["Ee", "Rere", "Rere"],
    studentChangeSis: ["dsd", "Dsds", "sd"],
    studentReturnDate: "",
    currentSymptoms: ["ewew", "ew", "Ee", "we"],
    currentSymptomsID: [],
    teacherNotifiedReturnDateID: "",
    teacherNotifiedReturnID: "",
    studentNegativeCovidTestID: "",
    studentReturnID: "",
    studentChangeSisID: ""
  }
};
