export const data = [
  {
    id: "ID_1",
    case_number: "",
    name: "john",
    post: "Teacher",
    grade: "10",
    cohort: "1",
    teacher: "t",
    current_status: "Tracked",
    date_started: "11-10-20",
    status: "yes"
  },
  {
    id: "ID_2",
    case_number: "",
    name: "john1",
    post: "Teacher",
    grade: "10",
    cohort: "1",
    teacher: "t",
    current_status: "Tracked",
    date_started: "11-10-20",
    status: "yes"
  },
  {
    id: "ID_3",
    case_number: "",
    name: "john2",
    post: "Teacher",
    grade: "10",
    cohort: "1",
    teacher: "t",
    current_status: "Tracked",
    date_started: "11-10-20",
    status: "yes"
  },
  {
    id: "ID_4",
    case_number: "",
    name: "john3",
    post: "Teacher",
    grade: "10",
    cohort: "1",
    teacher: "t",
    current_status: "Tracked",
    date_started: "11-10-20",
    status: "yes"
  },
  {
    id: "ID_5",
    case_number: "",
    name: "john4",
    post: "Teacher",
    grade: "10",
    cohort: "1",
    teacher: "t",
    current_status: "Tracked",
    date_started: "11-10-20",
    status: "yes"
  },
  {
    id: "ID_6",
    case_number: "",
    name: "john5",
    post: "Teacher",
    grade: "10",
    cohort: "1",
    teacher: "t",
    current_status: "Tracked",
    date_started: "11-10-20",
    status: "yes"
  },
  {
    id: "ID_7",
    case_number: "",
    name: "john6",
    post: "Teacher",
    grade: "10",
    cohort: "1",
    teacher: "t",
    current_status: "Tracked",
    date_started: "11-10-20",
    status: "yes"
  },
  {
    id: "ID_8",
    case_number: "",
    name: "john7",
    post: "Teacher",
    grade: "10",
    cohort: "1",
    teacher: "t",
    current_status: "Tracked",
    date_started: "11-10-20",
    status: "yes"
  },
  {
    id: "ID_9",
    case_number: "",
    name: "john8",
    post: "Teacher",
    grade: "10",
    cohort: "1",
    teacher: "t",
    current_status: "Returned",
    date_started: "11-10-20",
    status: "yes"
  } // eslint-disable-line
];
export const updateData = [
  {
    number: "1",
    name: "john",
    post: "Teacher",
    date_tracked: "10-10-20",
    date_notified: "10-10-20",
    date_of_contact: "10-10-20",
    s_o_covid: ["wdwd", "rew"],
    status: "yes"
  },
  {
    number: "2",
    name: "john",
    post: "Teacher",
    date_tracked: "10-10-20",
    date_notified: "10-10-20",
    date_of_contact: "10-10-20",
    s_o_covid: ["wdwd", "rew"],
    status: "yes"
  },
  {
    number: "3",
    name: "robin",
    post: "Teacher",
    date_tracked: "10-10-20",
    date_notified: "10-10-20",
    date_of_contact: "10-10-20",
    s_o_covid: ["wdwd", "rew"],
    status: "yes"
  },
  {
    number: "4",
    name: "robin",
    post: "Teacher",
    date_tracked: "10-10-20",
    date_notified: "10-10-20",
    date_of_contact: "10-10-20",
    s_o_covid: ["wdwd", "rew"],
    status: "yes"
  },
  {
    number: "5",
    name: "robin",
    post: "Teacher",
    date_tracked: "10-10-20",
    date_notified: "10-10-20",
    date_of_contact: "10-10-20",
    s_o_covid: ["wdwd", "rew"],
    status: "yes"
  } // eslint-disable-line
];
export const data3 = {
  initialData: {
    studentIDList: ["select1", "select2"],
    caseNumber: "",
    lastName: "",
    firstName: "",
    grade: ["select1", "select2", "select3"],
    teacher: ["select1", "select2", "select3"],
    isHome: true,
    PG: true,
    date: "",
    reference: "",
    selectSymptoms: ["select1", "select2", "select3"],
    temprature: ["select1", "select2", "select3"],
    affectedArea: ["select1", "select2", "select3"],
    isStafNotified: true,
    selectSymptomsID: [],
    studentID: "",
    teacherID: "",
    gradeID: "",
    tempratureID: "",
    affectedAreaID: ""
  },
  HourTracker: {
    checkInDate: "",
    status: ["Return to school", "Remote  Quarantine"],
    symptoms: ["select1", "select2", "select3"],
    changeRemote: ["select1", "select2", "select3"],
    teacherNotified: ["select1", "select2", "select3"],
    sisChangeConducted: ["select1", "select2", "select3"],
    handoutProvided: ["select1", "select2", "select3"],
    currentStutus: ["select1", "select2", "select3"],
    covidDate: "",
    currentStatus: ["select1", "select2"],
    statusID: "",
    symptomsID: [],
    changeRemoteID: "",
    teacherNotifiedID: "",
    sisChangeConductedID: "",
    currentStatusID: [],
    handoutProvidedID: ""
  },
  ReturnTracker: {
    checkInDate: "",
    anticipatedReturnDate: "",
    teacherNotifiedReturn: ["select1", "select2"],
    teacherNotifiedReturnDate: ["select1", "select2"],
    studentNegativeCovidTest: ["select1", "select2"],
    studentNegativeCovidTestDate: "",
    studentReturn: ["select1", "select2"],
    studentChangeSis: ["select1", "select2"],
    studentReturnDate: "",
    currentSymptoms: ["select1", "select2"],
    currentSymptomsID: [],
    teacherNotifiedReturnDateID: "",
    teacherNotifiedReturnID: "",
    studentNegativeCovidTestID: "",
    studentReturnID: "",
    studentChangeSisID: ""
  },
  error: {
    initialDataError: {
      selectSymptomsID: "",
      studentID: "",
      teacherID: "",
      caseNumber: "",
      lastName: "",
      firstName: "",
      date: "",
      reference: "",
      gradeId: "",
      studentGrade: "",
      tempratureID: "",
      affectedAreaID: ""
    },
    hourTrackerError: {
      covidDate: "",
      currentStatus: "",
      statusID: "",
      symptomsID: "",
      changeRemoteID: "",
      teacherNotifiedID: "",
      sisChangeConductedID: "",
      handoutProvidedID: "",
      currentStatusID: ""
    },
    returnTrackerError: {
      checkInDate: "",
      anticipatedReturnDate: "",
      studentNegativeCovidTestDate: "",
      studentReturnDate: "",
      teacherNotifiedReturnDateID: "",
      teacherNotifiedReturnID: "",
      studentNegativeCovidTestID: "",
      studentReturnID: "",
      studentChangeSisID: "",
      currentSymptomsID: ""
    }
  }
};
